### ISSUE TITLE
hdf5r vs. rhdf5

### ISSUE THREAD

**Issue by timz0605** [lentendu/NetworkNullHPC#22]
Hello!

It has come to my attention that there seem to be two hdf5 packages available in R. One is hdf5r, while the other one is rhdf5. In the `readme` file, you mentioned that we should install the `hdf5r` package. While in the script, it is trying to read R library calling `library(rhdf5)`. I was wondering if you could clarify this a bit more? Thank you!

**Comment by lentendu** [comment]
Thank you for spotting this mistake in the README, it is now corrected.
