### ISSUE TITLE
-m columns option not working, Error in match.arg

### ISSUE THREAD

**Issue by timz0605** [lentendu/NetworkNullHPC#24]
Hello,

While I was trying the `-m columns` option for choosing the null model, I encountered the below error code which causes the job submitted showing a status of `DependencyNeverSatisfied`
```
Error in match.arg(fixedmar, c("none", "rows", "columns", "both")) : 
  'arg' must be NULL or a character vector
Calls: permatfull -> match.arg
Execution halted
```
I was wondering if you could help look into this? Thank you!

**Comment by lentendu** [comment]
Hi, thanks for reporting this issue.
I have now fixed it with commit a67dc5d.
