### ISSUE TITLE
choosing null model using options from permatful in vegan

### ISSUE THREAD

**Issue by timz0605** [lentendu/NetworkNullHPC#25]
Hello @lentendu,

Thank you again for creating the script, and I have been making progress and getting results along the way. I have a quick question about the `-m null_model` when using the `permatfull` function from vegan. Although I have been looking for documentation regarding different options for `fixedmar`, almost none talked about the rationale of choosing one over the other. E.g., when to choose `row` vs. `column` vs. `both`. 

Therefore, I was wondering if you have had experienced with the options before? Also, I was curious of what you think about the options, for example, which one is better suited for analyzing OTU table? Thank you!

**Comment by lentendu** [comment]
The randomization algorithm provided correspond to the most commonly used in ecology (but see [Hardy 2008](https://doi.org/10.1111/j.1365-2745.2008.01421.x) for further description).
Null model selection depend on the type of dataset (abundance vs. occurrence, observation vs. molecular, counts vs. composition) and the hypothesis tested.
Here the code try to detect non-random species/OTUs associations, so the null model should be a community with a random occurrence of OTUs.
It is often suggested to maintain any other structural properties fix, e.g., OTU richness and number of occurrence of an OTU. 
I generally use `-m 2` which maintain the number of occurrence of a single OTU fix, and maintain the relative abundance of a single occurrence.
I have not tested the other options offered by `permatfull` myself, but I would suggest to prefer `both`.
You can read more about null model selection in [Molina & Stone (2020)](https://doi.org/10.1002/ecy.2945)
